# Generated by Django 4.2.4 on 2023-08-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodreadsAPP', '0002_alter_input_booklist_alter_input_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=2000)),
                ('password', models.CharField(max_length=2000)),
            ],
        ),
    ]
