# Generated by Django 4.2.4 on 2023-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodreadsAPP', '0003_recommendationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='findLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=2000)),
            ],
        ),
    ]
